### PR TITLE
invoice created with cashier creating order - add order items to orde…

### LINKED ISSUE #161: Cashier... Generate Invoice upon order creation

### PR DESCRIPTION
**Pull request by HMMK99**
…r creation

### CODE REVIEW

**Comment by HMMK99** [comment]
When cashier create the order and generate invoice.

is he the user or he choose from the users?

**Comment by HMMK99** [comment]
still tests for add

**Comment by HMMK99** [comment]
Screenshot from 2021-05-17 10-28-29

**Comment by HMMK99** [comment]
Screenshot from 2021-05-17 12-32-50

**Comment by HMMK99** [comment]
Screenshot from 2021-05-17 13-38-35

**Comment by HMMK99** [comment]
add permissions for invoice pdf and view pages

**Comment by shahwan42** [comment]
Can you hide the shop attribute if the user is a cashier, and programmatically assign the cahsier's shop to it?

**Comment by shahwan42** [comment]
also, 
resolve conflicts please

**Comment by HMMK99** [comment]
Screenshot from 2021-05-18 23-39-04

**Review by shahwan42 — DISMISSED** [review]

**Comment by shahwan42** [comment]
Review and merge @mmostafa74 please

**Review by shahwan42 — APPROVED** [review]

**Comment by shahwan42** [comment]
@mmostafa74 please review and merge...

**Review by mmostafa74 — APPROVED** [review]

**Pull request merged**
