### PR TITLE
Import products from excel

### LINKED ISSUE #174: Upload products using Excel sheets

### PR DESCRIPTION
**Pull request by HMMK99**
still needs validations

'name', 'price', 'stock', 'barcode', 'country_id', 'manufacturer_id', 'number_id', 'added_by', 'shop'

i used these fields in creating new products is it right? or some of them auto generated?

### CODE REVIEW

**Comment by HMMK99** [comment]
Screenshot from 2021-06-29 06-36-11
Screenshot from 2021-06-29 06-36-15

**Review by shahwan42 — DISMISSED** [review]
Seems fine. Could you please record a video so that we put it into the presentation?

**Comment by shahwan42** [comment]
added_by & shop are auto-generated based on the admin importing the file & for which shop like you did @HMMK99

**Comment by HMMK99** [comment]
> Seems fine. Could you please record a video so that we put it into the presentation?

I uploaded it on discord on web channel

**Review by shahwan42 — APPROVED** [review]

**Pull request merged**
