### PR TITLE
added only html and styles

### LINKED ISSUE #87: Cart View Django Template

### LINKED ISSUE #91: Cart View apply Ui Code

### PR DESCRIPTION
**Pull request by HMMK99**
added the templates and styles only for now.

### CODE REVIEW

**Review by shahwan42 — CHANGES_REQUESTED** [review]
Please continue and add logic to present the cart items in the cart view

**Comment by HMMK99** [comment]
Screenshot from 2021-04-22 09-40-21

**Comment by HMMK99** [comment]
also for the previous task in cart api, I edited the code to have 1 less filter and 1 less for loop.

**Comment by HMMK99** [comment]
Screenshot from 2021-05-01 12-39-25

**Review by mmostafa74 — APPROVED** [review]

**Pull request merged**
