### PR TITLE
list orders per shop for managers

### LINKED ISSUE #44: List Products per Shop for Managers/DECs accessing the dashboard
Products Shown in the dashboard must be in the Shop connected to Manager/DEC ONLY

This can be done After #43

### LINKED ISSUE #51: List Orders per Shop for Managers in the dashboard
After #43

### PR DESCRIPTION
**Pull request by ziadnabil**
Screenshot from 2021-05-17 02-45-31

Screenshot from 2021-05-17 02-45-43

Screenshot from 2021-05-17 02-45-59

### CODE REVIEW

**Review by shahwan42 — DISMISSED** [review]

**Comment by shahwan42** [comment]
Please resolve the conflicts

**Comment by shahwan42** [comment]
Can you hide the shop field and auto-assign it programmatically, you can use the currently authenticated user's shop?
You can consult @HMMK99 for how to do it. He did it before.

Good job so far!

**Comment by ziadnabil** [comment]
Screenshot from 2021-05-20 15-43-05

**Comment by mmostafa74** [comment]
please resolve conflicts

**Comment by mmostafa74** [comment]
please fix errors in tests @ziadnabil

**Review by mmostafa74 — APPROVED** [review]

**Pull request merged**
